name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf \
          libfuse2 \
          build-essential \
          curl \
          wget \
          file \
          libssl-dev \
          libgtk-3-dev
    
    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
    
    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'
    
    - name: Cache Typesense binary
      id: cache-typesense
      uses: actions/cache@v4
      with:
        path: typesense
        key: typesense-29.0-linux-amd64
    
    - name: Download Typesense binary for Linux
      if: steps.cache-typesense.outputs.cache-hit != 'true'
      run: |
        curl -O https://dl.typesense.org/releases/29.0/typesense-server-29.0-linux-amd64.tar.gz
        tar -xzf typesense-server-29.0-linux-amd64.tar.gz
        mkdir -p typesense
        mv typesense-server typesense/typesense-server-x86_64-unknown-linux-gnu
        rm typesense-server-29.0-linux-amd64.tar.gz typesense-server.md5.txt
    
    - name: Build
      run: cargo check --verbose --manifest-path src-tauri/Cargo.toml --color never

  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf \
          libfuse2 \
          build-essential \
          curl \
          wget \
          file \
          libssl-dev \
          libgtk-3-dev
    
    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
    
    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'
    
    - name: Cache Typesense binary
      id: cache-typesense
      uses: actions/cache@v4
      with:
        path: typesense
        key: typesense-29.0-linux-amd64
    
    - name: Download Typesense binary for Linux
      if: steps.cache-typesense.outputs.cache-hit != 'true'
      run: |
        curl -O https://dl.typesense.org/releases/29.0/typesense-server-29.0-linux-amd64.tar.gz
        tar -xzf typesense-server-29.0-linux-amd64.tar.gz
        mkdir -p typesense
        mv typesense-server typesense/typesense-server-x86_64-unknown-linux-gnu
        rm typesense-server-29.0-linux-amd64.tar.gz typesense-server.md5.txt
    
    - name: Run tests
      run: cargo test --verbose --manifest-path src-tauri/Cargo.toml --color never
